name: Schedule Test

on:
    schedule:
        - cron: "*/5 * * * *" # 5分ごとに変更
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Echo a message
              run: echo "Hello from the 5-minute schedule!"
